camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    deployment-resource-pattern: classpath*:/*.bpmn
    job-execution:
      enabled: false
    auto-deployment-enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_camunda
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update